Repository JECT-Study/PICK-O-Server, pull requests merged in 2024-02, with the labels that each got.

#15 feat: filetype enum값 추가
  src/main/java/balancetalk/domain/file/enums/FileType.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#13 feat: 신고 카테고리 항목 추가
  src/main/java/balancetalk/domain/report/enums/ReportCategory.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#11 feat: entity에 검증 어노테이션 추가
  src/main/java/balancetalk/domain/Notice.java
  src/main/java/balancetalk/domain/comment/entity/Comment.java
  src/main/java/balancetalk/domain/comment/entity/CommentLike.java
  src/main/java/balancetalk/domain/file/entity/File.java
  src/main/java/balancetalk/domain/file/enums/FileType.java
  src/main/java/balancetalk/domain/member/entity/Member.java
  src/main/java/balancetalk/domain/post/entity/BalanceOption.java
  src/main/java/balancetalk/domain/post/entity/Post.java
  src/main/java/balancetalk/domain/report/entity/Report.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#26 feat: 검증 애노테이션 추가
  src/main/java/balancetalk/module/Notice.java
  src/main/java/balancetalk/module/comment/domain/Comment.java
  src/main/java/balancetalk/module/file/domain/File.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/member/domain/Role.java
  src/main/java/balancetalk/module/post/domain/BalanceOption.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/domain/Tag.java
  src/main/java/balancetalk/module/report/domain/Report.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#28 게시글 작성 기능 구현
  build.gradle
  src/main/java/balancetalk/module/file/domain/File.java
  src/main/java/balancetalk/module/file/dto/FileDto.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/BalanceOption.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/domain/PostRepository.java
  src/main/java/balancetalk/module/post/domain/PostTag.java
  src/main/java/balancetalk/module/post/domain/Tag.java
  src/main/java/balancetalk/module/post/dto/BalanceOptionDto.java
  src/main/java/balancetalk/module/post/dto/PostRequestDto.java
  src/main/java/balancetalk/module/post/dto/PostResponseDto.java
  src/main/java/balancetalk/module/post/dto/PostTagDto.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
  src/test/java/balancetalk/module/post/application/PostServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 🗂️ db, 🧪 test, 👨🏻‍💻 backend

#39 게시글 CRUD 기능 구현
  src/main/java/balancetalk/module/file/domain/File.java
  src/main/java/balancetalk/module/file/dto/FileDto.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/member/presentation/MemberRepository.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/BalanceOption.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/domain/PostRepository.java
  src/main/java/balancetalk/module/post/domain/PostTag.java
  src/main/java/balancetalk/module/post/domain/Tag.java
  src/main/java/balancetalk/module/post/dto/BalanceOptionDto.java
  src/main/java/balancetalk/module/post/dto/PostRequestDto.java
  src/main/java/balancetalk/module/post/dto/PostResponseDto.java
  src/main/java/balancetalk/module/post/dto/PostTagDto.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
  src/test/java/balancetalk/module/post/application/PostServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#40 댓글 CRUD 기능 구현
  src/main/java/balancetalk/BalanceTalkApplication.java
  src/main/java/balancetalk/global/common/BaseTimeEntity.java
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/Comment.java
  src/main/java/balancetalk/module/comment/domain/CommentRepository.java
  src/main/java/balancetalk/module/comment/dto/CommentCreateRequest.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/comment/presentation/CommentController.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#49 투표 기능 예외 처리
  src/main/java/balancetalk/global/exception/BalanceTalkException.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/exception/ErrorResponse.java
  src/main/java/balancetalk/global/exception/GlobalExceptionHandler.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/vote/application/VoteService.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#62 Feat/58 bookmark add post
  src/main/java/balancetalk/module/post/application/BookmarkService.java
  src/main/java/balancetalk/module/post/domain/Bookmark.java
  src/main/java/balancetalk/module/post/domain/BookmarkRepository.java
  src/main/java/balancetalk/module/post/dto/BookmarkRequestDto.java
  src/main/java/balancetalk/module/post/presentation/BookmarkController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#64 북마크에 추가된 게시글 전체 목록 조회 기능 구현 완료
  src/main/java/balancetalk/module/post/application/BookmarkService.java
  src/main/java/balancetalk/module/post/dto/BookmarkResponseDto.java
  src/main/java/balancetalk/module/post/presentation/BookmarkController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#65 북마크 해제 기능 구현 완료
  src/main/java/balancetalk/module/post/application/BookmarkService.java
  src/main/java/balancetalk/module/post/domain/BookmarkRepository.java
  src/main/java/balancetalk/module/post/presentation/BookmarkController.java
Labels: ✨ feature, 👨🏻‍💻 backend, 🛠️ fix

#54 게시글 추천 기능 구현
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/PostLike.java
  src/main/java/balancetalk/module/post/domain/PostLikeRepository.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
  src/test/java/balancetalk/module/post/application/PostServiceTest.java
  src/test/java/balancetalk/module/vote/application/VoteServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#55 댓글 추천 기능 구현
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/CommentLike.java
  src/main/java/balancetalk/module/comment/domain/CommentLikeRepository.java
  src/main/java/balancetalk/module/comment/presentation/CommentController.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#52 댓글 기능 예외 처리
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/comment/presentation/CommentController.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#73 북마크 기능 예외 처리 구현 완료
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/post/application/BookmarkService.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/presentation/BookmarkController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#75 북마크 기능, 예외 처리 단위 테스트 구현 및 통과 완료
  src/test/java/balancetalk/module/post/application/BookmarkServiceTest.java
Labels: ✔︎ pull requests, 🧪 test, 👨🏻‍💻 backend

#69 회원 정보 조회 기능 구현
  build.gradle
  src/main/java/balancetalk/global/config/MyUserDetailService.java
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/member/domain/MemberRepository.java
  src/main/java/balancetalk/module/member/dto/JoinDto.java
  src/main/java/balancetalk/module/member/dto/LoginDto.java
  src/main/java/balancetalk/module/member/dto/LoginSuccessDto.java
  src/main/java/balancetalk/module/member/dto/MemberResponseDto.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/BalanceOption.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
  src/test/java/balancetalk/module/post/application/PostServiceTest.java
Labels: ✔︎ pull requests, 👨🏻‍💻 backend

#83 게시글 CRUD 에러 코드 추가
  src/main/java/balancetalk/global/exception/GlobalExceptionHandler.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/dto/JoinDto.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#81 멤버 삭제 기능 구현
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/dto/MemberResponseDto.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: ✔︎ pull requests, 🧪 test, 👨🏻‍💻 backend

#80 북마크 기능 구현 완료
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/post/application/BookmarkService.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/BalanceOption.java
  src/main/java/balancetalk/module/post/domain/Bookmark.java
  src/main/java/balancetalk/module/post/domain/BookmarkRepository.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/domain/PostLike.java
  src/main/java/balancetalk/module/post/domain/Tag.java
  src/main/java/balancetalk/module/post/dto/BalanceOptionDto.java
  src/main/java/balancetalk/module/post/dto/BookmarkRequestDto.java
  src/main/java/balancetalk/module/post/dto/BookmarkResponseDto.java
  src/main/java/balancetalk/module/post/dto/PostRequestDto.java
  src/main/java/balancetalk/module/post/dto/PostResponseDto.java
  src/main/java/balancetalk/module/post/dto/PostTagDto.java
  src/main/java/balancetalk/module/post/presentation/BookmarkController.java
  src/test/java/balancetalk/module/post/application/BookmarkServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#79 댓글 추천 취소 기능 구현
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/CommentLikeRepository.java
  src/main/java/balancetalk/module/comment/presentation/CommentController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#86 댓글 조회시 selectedOptionId 반환 기능 구현 완료
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/Comment.java
  src/main/java/balancetalk/module/comment/dto/CommentCreateRequest.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/vote/domain/VoteRepository.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#91 북마크 기능 스웨거에 추가
  src/main/java/balancetalk/module/post/dto/BookmarkRequestDto.java
  src/main/java/balancetalk/module/post/dto/BookmarkResponseDto.java
  src/main/java/balancetalk/module/post/presentation/BookmarkController.java
  src/main/java/balancetalk/module/vote/presentation/VoteController.java
Labels: 💻 deploy, 👨🏻‍💻 backend

#95 댓글 기능 단위 테스트 코드 수정 및 통과 완료
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Labels: ✔︎ pull requests, 🧪 test, 👨🏻‍💻 backend

#96 댓글 기능 단위 테스트 코드 수정 및 통과 완료
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Labels: ✔︎ pull requests, 🧪 test, 👨🏻‍💻 backend, 🛠️ fix

#98 이메일 발송 기능 구현
  build.gradle
  src/main/java/balancetalk/global/config/MyUserDetailService.java
  src/main/java/balancetalk/global/mail/application/MailService.java
  src/main/java/balancetalk/global/mail/dto/EmailRequest.java
  src/main/java/balancetalk/global/mail/presentation/MailController.java
  src/main/resources/application.yml
Labels: ✔︎ pull requests, 👨🏻‍💻 backend

#97 파일 업로드 기능 구현 완료
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/file/application/FileService.java
  src/main/java/balancetalk/module/file/domain/File.java
  src/main/java/balancetalk/module/file/domain/FileRepository.java
  src/main/java/balancetalk/module/file/dto/FileDto.java
  src/main/java/balancetalk/module/file/presentation/FileController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#102 파일 다운로드 기능 구현 완료
  src/main/java/balancetalk/module/file/application/FileService.java
  src/main/java/balancetalk/module/file/presentation/FileController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#104 Redis 설정
  build.gradle
  src/main/java/balancetalk/global/config/RedisConfig.java
  src/main/java/balancetalk/global/redis/application/RedisService.java
  src/main/resources/application.yml
  src/test/java/balancetalk/global/redis/application/RedisServiceTest.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Labels: ✔︎ pull requests, 👨🏻‍💻 backend

#109 회원 정보 수정 닉네임 / 패스워드 분리
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/member/dto/MemberUpdateDto.java
  src/main/java/balancetalk/module/member/dto/NicknameUpdate.java
  src/main/java/balancetalk/module/member/dto/PasswordUpdate.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
  src/main/resources/application.yml
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: ✔︎ pull requests, 🪄 refactor, 🧪 test, 👨🏻‍💻 backend

#114 리프레시 토큰 추가 구현 및 전체적인 jwt 로직 수정
  src/main/java/balancetalk/global/config/MyUserDetailService.java
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/member/dto/JoinDto.java
  src/main/java/balancetalk/module/member/dto/LoginSuccessDto.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#138 회원 정보에서 ip 제거
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/member/dto/JoinDto.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
Labels: ✔︎ pull requests, 🪄 refactor, 👨🏻‍💻 backend

#124 엑세스 토큰 만료 시 리프레시 토큰으로 액세스 토큰 재발급 하는 기능 추가
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/dto/LoginSuccessDto.java
  src/main/java/balancetalk/module/member/dto/TokenDto.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: ✔︎ pull requests, 👨🏻‍💻 backend

#135 게시글 단건, 전체 조회 API 응답에 누락된 필드 추가
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/dto/PostResponseDto.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#134 회원 정보 수정, 삭제 리팩토링
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/domain/MemberRepository.java
  src/main/java/balancetalk/module/member/dto/LoginSuccessDto.java
  src/main/java/balancetalk/module/member/dto/MemberResponseDto.java
  src/main/java/balancetalk/module/member/dto/TokenDto.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
Labels: ✔︎ pull requests, 🪄 refactor, 👨🏻‍💻 backend

#133 답글 작성 기능 구현 완료
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/Comment.java
  src/main/java/balancetalk/module/comment/dto/ReplyCreateRequest.java
  src/main/java/balancetalk/module/comment/presentation/CommentController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend
