Repository JECT-Study/PICK-O-Server, pull requests merged in 2024-08, with the labels that each got.

#445 SSE 적용 실시간 알림 기능 구현
  build.gradle
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/notification/application/NotificationService.java
  src/main/java/balancetalk/global/notification/domain/Notification.java
  src/main/java/balancetalk/global/notification/domain/NotificationRepository.java
  src/main/java/balancetalk/global/notification/presentation/NotificationController.java
Labels: ✨ feature

#449 댓글 관련 실시간 알림 기능 구현 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/notification/domain/NotificationMessage.java
  src/main/java/balancetalk/like/application/CommentLikeService.java
Labels: ✨ feature, 👨🏻‍💻 backend

#447 멤버 단위 테스트 코드 작성
  src/test/java/balancetalk/member/application/MemberServiceTest.java
Labels: 🧪 test, 👨🏻‍💻 backend

#456 톡픽 상세 조회 응답에 필드 추가
  src/main/java/balancetalk/bookmark/application/BookmarkTalkPickService.java
  src/main/java/balancetalk/bookmark/domain/BookmarkRepository.java
  src/main/java/balancetalk/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/balancetalk/bookmark/domain/repository/BookmarkRepositoryCustom.java
  src/main/java/balancetalk/bookmark/domain/repository/BookmarkRepositoryImpl.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#454 톡픽 북마크 기능 단위 테스트
  src/test/java/balancetalk/bookmark/application/BookmarkTalkPickServiceTest.java
  src/test/java/balancetalk/bookmark/domain/BookmarkGeneratorTest.java
  src/test/java/balancetalk/talkpick/domain/TalkPickValidatorTest.java
Labels: 🧪 test, 👨🏻‍💻 backend

#459 톡픽 목록 조회 기능 구현
  src/main/java/balancetalk/bookmark/domain/repository/BookmarkRepositoryCustom.java
  src/main/java/balancetalk/bookmark/domain/repository/BookmarkRepositoryImpl.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryCustom.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#461 북마크 관련 로직 개선
  src/main/java/balancetalk/bookmark/application/BookmarkTalkPickService.java
  src/main/java/balancetalk/bookmark/domain/BookmarkRepository.java
  src/main/java/balancetalk/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/domain/TalkPickValidator.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/test/java/balancetalk/bookmark/application/BookmarkTalkPickServiceTest.java
  src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
  src/test/java/balancetalk/talkpick/domain/TalkPickValidatorTest.java
Labels: ✨ feature, 🪄 refactor, 🧪 test, 👨🏻‍💻 backend

#463 톡픽 상세 조회 API 응답에 수정 여부 필드 추가
  src/main/java/balancetalk/bookmark/domain/repository/BookmarkRepositoryCustom.java
  src/main/java/balancetalk/bookmark/domain/repository/BookmarkRepositoryImpl.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#465 톡픽 목록 조회 기능에 페이징 기본 옵션 추가
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#467 인기 톡픽 조회 기능 구현
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryCustom.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#473 밸런스 게임 투표 작업
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameReader.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/global/jwt/GuestOrApiMemberArgumentResolver.java
  src/main/java/balancetalk/member/dto/GuestOrApiMember.java
  src/main/java/balancetalk/vote/application/VoteGameService.java
  src/main/java/balancetalk/vote/dto/VoteGameDto.java
  src/main/java/balancetalk/vote/presentation/VoteGameController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#478 이미 북마크한 톡픽에 더 이상 북마크할 수 없다는 예외 처리 추가
  src/main/java/balancetalk/bookmark/application/BookmarkTalkPickService.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/test/java/balancetalk/bookmark/application/BookmarkTalkPickServiceTest.java
Labels: 👨🏻‍💻 backend, 🛠️ fix

#479 마이페이지 - 내가 저장한, 투표한 톡픽 조회 구현
  src/main/java/balancetalk/bookmark/domain/BookmarkRepository.java
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/member/presentation/MyPageController.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/vote/domain/VoteRepository.java
Labels: 👨🏻‍💻 backend

#481 마이페이지 - 내가 댓글단, 작성한 톡픽 조회 기능 구현 완료
  src/main/java/balancetalk/bookmark/domain/BookmarkRepository.java
  src/main/java/balancetalk/comment/domain/CommentRepository.java
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/member/presentation/MyPageController.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
Labels: ✨ feature, 👨🏻‍💻 backend

#484 레디스 코드 삭제 및 이메일 발송 로직 리팩토링
  build.gradle
  src/main/java/balancetalk/authmail/application/MailService.java
  src/main/java/balancetalk/authmail/dto/EmailRequest.java
  src/main/java/balancetalk/global/caffeine/CacheType.java
  src/main/java/balancetalk/global/config/EmbeddedRedisConfig.java
  src/main/java/balancetalk/global/config/RedisConfig.java
  src/main/java/balancetalk/global/redis/application/RedisService.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#485 톡픽 생성, 수정, 삭제 기능 구현
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
  src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#488 톡픽 상세조회 API의 응답 중 수정일을 lastModifiedAt이 아닌 editedAt으로 변경
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#493 톡픽 상세 조회 API의 응답에서 수정일을 생성일로 변경
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#495 밸런스 게임 북마크 API 작업
  src/main/java/balancetalk/bookmark/application/BookmarkGameService.java
  src/main/java/balancetalk/bookmark/presentation/BookmarkGameController.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/member/domain/Member.java
Labels: ✨ feature, 👨🏻‍💻 backend

#499 톡픽 임시 저장 기능 구현
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/talkpick/application/TempTalkPickService.java
  src/main/java/balancetalk/talkpick/domain/TempTalkPick.java
  src/main/java/balancetalk/talkpick/domain/repository/TempTalkPickRepository.java
  src/main/java/balancetalk/talkpick/dto/TempTalkPickDto.java
  src/main/java/balancetalk/talkpick/presentation/TempTalkPickController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#497 밸런스 게임 조회 시 북마크 여부 추가
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/presentation/GameController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#505 이미지 업로드 기능 개선
  src/main/java/balancetalk/file/application/FileService.java
  src/main/java/balancetalk/file/domain/File.java
  src/main/java/balancetalk/file/domain/FileProcessor.java
  src/main/java/balancetalk/file/domain/FileType.java
  src/main/java/balancetalk/file/domain/MultipartFiles.java
  src/main/java/balancetalk/file/dto/UploadFileResponse.java
  src/main/java/balancetalk/file/presentation/FileController.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/test/java/balancetalk/file/domain/FileProcessorTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#494 마이페이지 - 밸런스 게임 조회 기능 구현 및 톡픽 조회 일부 기능 수정
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/comment/domain/CommentRepository.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/repository/GameRepository.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/global/notification/presentation/NotificationController.java
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/member/presentation/MyPageController.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/vote/domain/VoteRepository.java
Labels: ✨ feature, 👨🏻‍💻 backend

#511 로그 파일 네이밍 변경
  src/main/resources/logs/log4j2-dev.yml
Labels: 👨🏻‍💻 backend, 🛠️ fix

#514 톡픽 상세 조회 API 응답에 이미지 URL 추가
  src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#516 [톡픽 임시 저장 API] 이미지 관련 정보 추가
  src/main/java/balancetalk/file/domain/FileType.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/application/TempTalkPickService.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/domain/TempTalkPick.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/talkpick/dto/TempTalkPickDto.java
Labels: ✨ feature, 👨🏻‍💻 backend

#519 임시 저장했던 톡픽 등록 시 파일 타입을 TALK_PICK으로 변경
  src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/application/TempTalkPickService.java
Labels: ✨ feature, 👨🏻‍💻 backend

#520 GameOption 엔티티 생성 및 매핑 정보 변경
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameOption.java
  src/main/java/balancetalk/game/domain/GameTopic.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/dto/GameOptionDto.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/vote/application/VoteGameService.java
  src/main/java/balancetalk/vote/domain/Vote.java
  src/main/java/balancetalk/vote/domain/VoteRepository.java
  src/main/java/balancetalk/vote/dto/VoteGameDto.java
Labels: 👨🏻‍💻 backend

#527 이미지 제거 기능 구현
  src/main/java/balancetalk/file/application/FileService.java
  src/main/java/balancetalk/file/domain/File.java
  src/main/java/balancetalk/file/domain/repository/FileRepository.java
  src/main/java/balancetalk/file/presentation/FileController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#528 마이페이지 컨텐츠 반환 시 DTO에 마이페이지 등록 날짜 포함 구현 완료
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/member/presentation/MyPageController.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
Labels: ✨ feature, 👨🏻‍💻 backend

#534 오늘의 톡픽 조회 쿼리 개선
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
Labels: ✨ feature, 👨🏻‍💻 backend

#536 소셜 로그인 api 추가
  src/main/java/balancetalk/member/presentation/Oauth2Controller.java
Labels: ✨ feature, 👨🏻‍💻 backend

#540 기존 알림 기능 개선 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/global/notification/application/NotificationService.java
  src/main/java/balancetalk/global/notification/domain/Notification.java
  src/main/java/balancetalk/global/notification/domain/NotificationMessage.java
  src/main/java/balancetalk/global/notification/domain/NotificationTitleCategory.java
  src/main/java/balancetalk/global/notification/dto/NotificationDto.java
  src/main/java/balancetalk/like/application/CommentLikeService.java
Labels: ✨ feature, 👨🏻‍💻 backend

#543 밸런스 게임 생성 시 누락된 북마크, 조회수 값 추가
  src/main/java/balancetalk/game/dto/GameDto.java
Labels: 👨🏻‍💻 backend, 🛠️ fix

#546 memberId 필드가 보이지 않도록 수정
  src/main/java/balancetalk/bookmark/presentation/BookmarkGameController.java
  src/main/java/balancetalk/bookmark/presentation/BookmarkTalkPickController.java
Labels: 🧹 cleanup, 👨🏻‍💻 backend

#550 GuestOrAPi 에서도 memberId를 가져오도록 수정
  src/main/java/balancetalk/global/utils/LoggingAspect.java
Labels: 🐛 bug, 👨🏻‍💻 backend

#542 내가 작성한 톡픽 저장 수 알림, 내가 작성한 톡픽 투표 수 알림 기능 구현 완료
  src/main/java/balancetalk/bookmark/application/BookmarkTalkPickService.java
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/global/notification/domain/NotificationMessage.java
  src/main/java/balancetalk/global/notification/domain/NotificationStandard.java
  src/main/java/balancetalk/like/application/CommentLikeService.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/vote/application/VoteTalkPickService.java
Labels: ✨ feature, 👨🏻‍💻 backend

#557 마이페이지 추가 정보 반환 구현
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/member/presentation/MyPageController.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
Labels: ✨ feature, 👨🏻‍💻 backend

#559 마이페이지 페이지네이션 size 적용되지 않는 에러 해결
  src/main/java/balancetalk/bookmark/domain/BookmarkRepository.java
  src/main/java/balancetalk/comment/domain/CommentRepository.java
  src/main/java/balancetalk/game/domain/repository/GameRepository.java
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java
  src/main/java/balancetalk/vote/domain/TalkPickVoteRepository.java
  src/main/java/balancetalk/vote/domain/VoteRepository.java
Labels: 👨🏻‍💻 backend, 🛠️ fix
