Repository JECT-Study/PICK-O-Server, pull requests merged in 2024-12, with the labels that each got.

#775 밸런스 게임 임시저장 시 파일 중복 오류 해결
  src/main/java/balancetalk/file/domain/repository/FileRepository.java
  src/main/java/balancetalk/game/application/TempGameService.java
  src/main/java/balancetalk/game/domain/TempGameOption.java
  src/main/java/balancetalk/game/domain/TempGameSet.java
  src/main/java/balancetalk/game/dto/TempGameOptionDto.java
  src/main/java/balancetalk/game/dto/TempGameSetDto.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
Labels: D-0

#783 feat: httpOnly = false, 도메인 주소를 설정하여 쿠키를 보내주도록 구현
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
Labels: D-0

#788 로그인 후 500에러 발생
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
Labels: 🐛 bug, D-0

#793 provider를 통해 member를 조회하도록 수정
  src/main/java/balancetalk/global/oauth2/service/CustomOAuth2UserService.java
Labels: 🐛 bug, D-0

#790 밸런스 게임, 임시 밸런스 게임 엔티티, 밸런스게임 마이페이지, 밸런스게임 검색에서 imgUrl 필드 제거
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/application/SearchGameService.java
  src/main/java/balancetalk/game/application/TempGameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameOption.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/game/domain/TempGameOption.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/dto/GameOptionDto.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/game/dto/SearchGameResponse.java
  src/main/java/balancetalk/game/dto/TempGameDto.java
  src/main/java/balancetalk/game/dto/TempGameOptionDto.java
  src/main/java/balancetalk/game/dto/TempGameSetDto.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/member/application/MyPageService.java
Labels: ✨ feature, D-0

#796 READ_ONLY accesMode를 통해 요청을 보낼 때 필드값이 보이지 않도록 수정
  src/main/java/balancetalk/game/dto/GameOptionDto.java
  src/main/java/balancetalk/game/dto/TempGameOptionDto.java
Labels: ✨ feature, D-0

#798 임시저장 시 필드값이나 게임 갯수가 모자라도 저장되도록 구현
  src/main/java/balancetalk/game/application/TempGameService.java
  src/main/java/balancetalk/game/domain/TempGame.java
  src/main/java/balancetalk/game/domain/TempGameOption.java
  src/main/java/balancetalk/game/domain/TempGameSet.java
  src/main/java/balancetalk/game/dto/TempGameSetDto.java
Labels: ✨ feature, D-0

#802 소셜로그인, 일반로그인 여부 구분 및 리다이렉트 추가
  src/main/java/balancetalk/global/oauth2/CustomSuccessHandler.java
  src/main/java/balancetalk/global/oauth2/dto/CustomOAuth2User.java
  src/main/java/balancetalk/global/oauth2/dto/Oauth2Dto.java
  src/main/java/balancetalk/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/member/domain/SignupType.java
  src/main/java/balancetalk/member/dto/MemberDto.java
Labels: ✨ feature, D-0

#812 @NotBlank 삭제
  src/main/java/balancetalk/game/domain/Game.java
Labels: ✨ feature, D-0

#806 컬럼 제약조건 및 DB 동기화를 위한 엔티티 클래스 수정
  src/main/java/balancetalk/bookmark/domain/GameBookmark.java
  src/main/java/balancetalk/bookmark/domain/TalkPickBookmark.java
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/file/domain/File.java
  src/main/java/balancetalk/game/domain/GameOption.java
  src/main/java/balancetalk/global/oauth2/CustomSuccessHandler.java
  src/main/java/balancetalk/like/domain/Like.java
  src/main/java/balancetalk/report/application/ReportCommentService.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/domain/TempTalkPick.java
  src/main/java/balancetalk/vote/domain/GameVote.java
  src/main/java/balancetalk/vote/domain/TalkPickVote.java
Labels: 🗂️ db, 🪄 refactor, 🛠️ fix, D-0

#820 톡픽 답글 작성 불가 이슈 해결
  src/main/java/balancetalk/comment/dto/CommentDto.java
Labels: ✨ feature, D-0

#827 토큰 재발급 로직 리팩토링
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/presentation/MemberController.java
Labels: ✨ feature, D-0

#829 변경된 요구사항에 따른 톡픽 본문 요약 기능 구현
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/talkpick/application/SummaryContentService.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/domain/SummaryStatus.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/domain/TalkPickSummarizer.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/talkpick/dto/fields/BaseTalkPickFields.java
  src/main/java/balancetalk/talkpick/presentation/SummaryContentController.java
Labels: ⚙️ chore, ✨ feature, 🪄 refactor, D-0
