Repository JECT-Study/PICK-O-Server, pull requests merged in 2024-07, with the labels that each got.

#362 공통 응답 포맷 롤백
  src/main/java/balancetalk/comment/presentation/CommentController.java
  src/main/java/balancetalk/game/presentation/GameBookmarkController.java
  src/main/java/balancetalk/game/presentation/GameController.java
  src/main/java/balancetalk/global/common/ApiResponse.java
  src/main/java/balancetalk/global/exception/ErrorResponse.java
  src/main/java/balancetalk/global/exception/GlobalExceptionHandler.java
  src/main/java/balancetalk/like/presentation/LikeController.java
  src/main/java/balancetalk/like/presentation/LikeTalkPickController.java
  src/main/java/balancetalk/member/presentation/MemberController.java
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
  src/main/java/balancetalk/talkpick/presentation/TodayTalkPickController.java
  src/main/java/balancetalk/vote/presentation/VoteTalkPickController.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#364 API 명세 수정(댓글, 댓글 좋아요) 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/comment/presentation/CommentController.java
  src/main/java/balancetalk/like/presentation/LikeController.java
Labels: 😓 help wanted, 👨🏻‍💻 backend, 🛠️ fix

#368 댓글 좋아요, 좋아요 취소 구현 완료
  src/main/java/balancetalk/comment/presentation/CommentController.java
  src/main/java/balancetalk/like/application/CommentLikeService.java
  src/main/java/balancetalk/like/domain/Like.java
  src/main/java/balancetalk/like/domain/LikeRepository.java
  src/main/java/balancetalk/like/dto/LikeDto.java
  src/main/java/balancetalk/like/presentation/LikeController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#373 API 명세서 중 톡픽 관련 내용 수정
  src/main/java/balancetalk/bookmark/domain/Bookmark.java
  src/main/java/balancetalk/bookmark/presentation/BookmarkTalkPickController.java
  src/main/java/balancetalk/like/domain/Like.java
  src/main/java/balancetalk/like/domain/LikeType.java
  src/main/java/balancetalk/like/dto/LikeDto.java
  src/main/java/balancetalk/like/presentation/LikeController.java
  src/main/java/balancetalk/like/presentation/LikeTalkPickController.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDetailResponse.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/talkpick/dto/TalkPickRequest.java
  src/main/java/balancetalk/talkpick/dto/TalkPickResponse.java
  src/main/java/balancetalk/talkpick/dto/TodayTalkPickDto.java
  src/main/java/balancetalk/talkpick/dto/TodayTalkPickResponse.java
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
  src/main/java/balancetalk/talkpick/presentation/TodayTalkPickController.java
  src/main/java/balancetalk/vote/presentation/VoteTalkPickController.java
Labels: ⚙️ chore, 🪄 refactor, 👨🏻‍💻 backend

#369 밸런스 게임 API 명세서 수정 및 dto 클래스 통합
  src/main/java/balancetalk/authmail/dto/EmailRequest.java
  src/main/java/balancetalk/authmail/dto/EmailVerification.java
  src/main/java/balancetalk/bookmark/controller/BookmarkGameController.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/dto/GameDetailResponse.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/dto/GameRequest.java
  src/main/java/balancetalk/game/dto/GameResponse.java
  src/main/java/balancetalk/game/presentation/GameController.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/dto/JoinRequest.java
  src/main/java/balancetalk/member/dto/LoginRequest.java
  src/main/java/balancetalk/member/dto/MemberDto.java
  src/main/java/balancetalk/member/dto/MemberResponse.java
  src/main/java/balancetalk/member/presentation/MemberController.java
  src/main/java/balancetalk/vote/dto/VoteDto.java
  src/main/java/balancetalk/vote/dto/VoteRequest.java
  src/main/java/balancetalk/vote/dto/VoteResponse.java
  src/main/java/balancetalk/vote/presentation/VoteGameController.java
  src/main/java/balancetalk/vote/presentation/VoteTalkPickController.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: ⚙️ chore, 🪄 refactor, 👨🏻‍💻 backend

#376 댓글 좋아요 기능 예외 처리 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/exception/GlobalExceptionHandler.java
  src/main/java/balancetalk/like/application/CommentLikeService.java
  src/main/java/balancetalk/like/domain/LikeRepository.java
  src/main/java/balancetalk/like/dto/LikeDto.java
  src/main/java/balancetalk/like/presentation/LikeController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend, 🛠️ fix

#380 오늘의 톡픽 조회 기능 구현
  build.gradle
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/global/config/QuerydslConfig.java
  src/main/java/balancetalk/like/application/CommentLikeService.java
  src/main/java/balancetalk/talkpick/application/TodayTalkPickService.java
  src/main/java/balancetalk/talkpick/domain/TalkPickRepository.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryCustom.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
  src/main/java/balancetalk/talkpick/dto/TodayTalkPickDto.java
  src/main/java/balancetalk/talkpick/presentation/TodayTalkPickController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#381 답글 작성 기능 구현 및 예외 처리 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/comment/presentation/CommentController.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#382 댓글 예외 처리 및 Code CleanUp 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/comment/presentation/CommentController.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/exception/GlobalExceptionHandler.java
  src/main/java/balancetalk/vote/domain/VoteOption.java
Labels: ✔︎ pull requests, ✨ feature, 🧹 cleanup, 👨🏻‍💻 backend

#385 댓글 좋아요/좋아요 취소 URI 수정 및 추가 예외 처리 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/like/application/CommentLikeService.java
  src/main/java/balancetalk/like/presentation/LikeController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#388 회원 시큐리티 로직 개선
  src/main/java/balancetalk/global/config/CustomUserDetails.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/application/MyUserDetailService.java
  src/main/java/balancetalk/member/domain/CustomUserDetails.java
  src/main/java/balancetalk/member/domain/Member.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#391 Argument Resolver를 사용하여 중복 코드 제거
  src/main/java/balancetalk/global/config/WebConfig.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/global/jwt/UserArgumentResolver.java
  src/main/java/balancetalk/global/utils/AuthPrincipal.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/dto/MemberDto.java
  src/main/java/balancetalk/member/presentation/MemberController.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#398 ERD 변경에 따른 Like 엔티티 수정 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/comment/domain/CommentRepository.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/like/application/CommentLikeService.java
  src/main/java/balancetalk/like/domain/Like.java
  src/main/java/balancetalk/like/domain/LikeRepository.java
  src/main/java/balancetalk/like/dto/LikeDto.java
Labels: ✔︎ pull requests, 🪄 refactor, 👨🏻‍💻 backend

#401 변경된 ERD에 따라 북마크 엔티티 수정
  src/main/java/balancetalk/bookmark/domain/Bookmark.java
  src/main/java/balancetalk/bookmark/presentation/BookmarkGameController.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#404 소셜 로그인 시 임시 비밀번호 저장 및 닉네임 처리
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/global/oauth2/dto/Oauth2Dto.java
  src/main/java/balancetalk/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/member/dto/MemberDto.java
Labels: ✨ feature, 👨🏻‍💻 backend

#410 댓글 좋아요 API URI 수정
  src/main/java/balancetalk/like/presentation/LikeController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#411 변경된 요구사항에 따라 오늘의 톡픽 조회 로직 수정
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
Labels: ✨ feature, 👨🏻‍💻 backend

#414 ArgumentResolver 로직 분리 및 JwtFilter 수정
  src/main/java/balancetalk/global/config/WebConfig.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/jwt/ApiMemberArgumentResolver.java
  src/main/java/balancetalk/global/jwt/GuestOrApiMemberArgumentResolver.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/global/oauth2/CustomSuccessHandler.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/application/MyUserDetailService.java
  src/main/java/balancetalk/member/dto/ApiMember.java
  src/main/java/balancetalk/member/dto/GuestOrApiMember.java
  src/main/java/balancetalk/member/dto/MemberDto.java
  src/main/java/balancetalk/member/presentation/MemberController.java
Labels: ✨ feature, 🪄 refactor, 👨🏻‍💻 backend

#415 톡픽 상세 조회 기능 구현
  src/main/java/balancetalk/bookmark/domain/Bookmark.java
  src/main/java/balancetalk/bookmark/domain/BookmarkType.java
  src/main/java/balancetalk/global/config/WebConfig.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/jwt/ApiMemberArgumentResolver.java
  src/main/java/balancetalk/global/oauth2/CustomSuccessHandler.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/domain/Summary.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/domain/TalkPickReader.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
  src/main/java/balancetalk/talkpick/dto/SummaryDto.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/talkpick/dto/TodayTalkPickDto.java
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
  src/main/java/balancetalk/vote/domain/Vote.java
Labels: ✨ feature, 👨🏻‍💻 backend

#420 회원 로직 변경에 따른 기존 댓글, 댓글 좋아요 코드 수정 및 추가 기능 구현
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/presentation/CommentController.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/like/application/CommentLikeService.java
  src/main/java/balancetalk/like/domain/Like.java
  src/main/java/balancetalk/like/presentation/LikeController.java
Labels: ✔︎ pull requests, ✨ feature, 🧹 cleanup, 👨🏻‍💻 backend

#419 톡픽 상세 조회 기능에 대한 단위 테스트 작성
  src/main/java/balancetalk/talkpick/domain/Summary.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
  src/test/java/balancetalk/talkpick/domain/TalkPickReaderTest.java
Labels: 🧪 test, 👨🏻‍💻 backend

#422 톡픽 투표 기능 구현
  build.gradle
  src/main/java/balancetalk/global/config/SwaggerConfig.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
  src/main/java/balancetalk/vote/application/VoteTalkPickService.java
  src/main/java/balancetalk/vote/domain/Vote.java
  src/main/java/balancetalk/vote/domain/VoteType.java
  src/main/java/balancetalk/vote/dto/VoteGameDto.java
  src/main/java/balancetalk/vote/dto/VoteTalkPickDto.java
  src/main/java/balancetalk/vote/presentation/VoteGameController.java
  src/main/java/balancetalk/vote/presentation/VoteTalkPickController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#424 톡픽 상세 조회 API 응답에 각 선택지에 대한 투표수 필드 추가
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/talkpick/dto/TodayTalkPickDto.java
  src/main/java/balancetalk/vote/domain/Vote.java
  src/main/java/balancetalk/vote/presentation/VoteTalkPickController.java
  src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#427 톡픽 투표 기능 단위 테스트
  src/test/java/balancetalk/vote/application/VoteTalkPickServiceTest.java
  src/test/java/balancetalk/vote/domain/VoteTest.java
Labels: 🧪 test, 👨🏻‍💻 backend

#431 밸런스 게임 API 구현
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/repository/GameRepository.java
  src/main/java/balancetalk/game/domain/repository/GameTopicRepository.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/presentation/GameController.java
  src/main/java/balancetalk/game/presentation/GameTopicController.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/vote/application/VoteTalkPickService.java
  src/main/java/balancetalk/vote/domain/Vote.java
Labels: ✨ feature, 👨🏻‍💻 backend

#429 댓글, 댓글 좋아요 스웨거에 ApiMember, GuestOrApiMember hidden 처리 완료
  src/main/java/balancetalk/comment/presentation/CommentController.java
  src/main/java/balancetalk/like/presentation/LikeController.java
Labels: 👨🏻‍💻 backend, 🛠️ fix

#433 밸런스 게임 최신순, 인기순 조회 로직 구현
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/repository/GameRepository.java
  src/main/java/balancetalk/game/presentation/GameController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#437 밸런스 게임 이미지 등록 구현
  src/main/java/balancetalk/file/domain/FileRepository.java
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/dto/GameDto.java
Labels: ✨ feature, 👨🏻‍💻 backend

#435 신고 기능 추가 구현 완료
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/report/application/ReportCommentService.java
  src/main/java/balancetalk/report/domain/Report.java
  src/main/java/balancetalk/report/domain/ReportReason.java
  src/main/java/balancetalk/report/domain/ReportRepository.java
  src/main/java/balancetalk/report/domain/ReportType.java
  src/main/java/balancetalk/report/dto/ReportDto.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend, 🛠️ fix

#439 회원 조회 방식을 email이 아닌 id로 변경
  src/main/java/balancetalk/global/jwt/ApiMemberArgumentResolver.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/global/oauth2/CustomSuccessHandler.java
  src/main/java/balancetalk/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/balancetalk/member/application/MyUserDetailService.java
  src/main/java/balancetalk/member/dto/ApiMember.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#441 회원 이미지 관련 작업
  src/main/java/balancetalk/file/domain/FileRepository.java
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/member/dto/MemberDto.java
  src/main/java/balancetalk/member/presentation/MemberController.java
Labels: ✨ feature, 👨🏻‍💻 backend
