Repository JECT-Study/PICK-O-Server, pull requests merged in 2024-11, with the labels that each got.

#675 비밀번호 재설정 로직 수정
  src/main/java/balancetalk/authmail/application/MailService.java
  src/main/java/balancetalk/authmail/dto/EmailDto.java
  src/main/java/balancetalk/authmail/dto/EmailRequest.java
  src/main/java/balancetalk/authmail/dto/EmailVerification.java
  src/main/java/balancetalk/authmail/presentation/MailController.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/oauth2/CustomSuccessHandler.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/dto/MemberDto.java
  src/main/java/balancetalk/member/presentation/MemberController.java
  src/test/java/balancetalk/member/application/MemberServiceTest.java
Labels: 🪄 refactor, D-0

#679 네이밍 변경
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/application/TempGameService.java
  src/main/java/balancetalk/game/domain/repository/MainTagRepository.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
Labels: D-0

#673 S3 디렉토리 구조 변경 및 관련 로직 개선
  src/main/java/balancetalk/file/application/FileService.java
  src/main/java/balancetalk/file/domain/File.java
  src/main/java/balancetalk/file/domain/FileHandler.java
  src/main/java/balancetalk/file/domain/FileProcessor.java
  src/main/java/balancetalk/file/domain/FileType.java
  src/main/java/balancetalk/file/domain/repository/FileRepository.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java
  src/main/java/balancetalk/file/dto/UploadFileResponse.java
  src/main/java/balancetalk/file/presentation/FileController.java
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/application/TempGameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/game/domain/TempGame.java
  src/main/java/balancetalk/game/domain/TempGameSet.java
  src/main/java/balancetalk/game/domain/repository/TempGameRepository.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/dto/GameOptionDto.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/game/dto/TempGameDto.java
  src/main/java/balancetalk/game/dto/TempGameOptionDto.java
  src/main/java/balancetalk/game/dto/TempGameSetDto.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/application/TempTalkPickService.java
  src/main/java/balancetalk/talkpick/domain/repository/SearchTalkPickRepositoryImpl.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/talkpick/dto/TempTalkPickDto.java
  src/test/java/balancetalk/file/domain/FileProcessorTest.java
Labels: ✨ feature, 🪄 refactor, D-0

#683 회원 가입 인증 API, 비밀번호 재설정 API 분리
  src/main/java/balancetalk/authmail/application/MailService.java
  src/main/java/balancetalk/authmail/presentation/MailController.java
Labels: 🪄 refactor

#685 밸런스게임 생성(or 수정 or 임시 저장) API 요청 시 GAME_OPTION 테이블의 GAME_ID가 null로 저장되는 이슈 해결
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/application/TempGameService.java
  src/main/java/balancetalk/game/dto/TempGameSetDto.java
Labels: 🛠️ fix, D-0

#687 활동 정보 조회 API 생성
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/member/dto/MemberDto.java
  src/main/java/balancetalk/member/presentation/MyPageController.java
  src/main/java/balancetalk/vote/presentation/VoteGameController.java
Labels: ✨ feature, D-0

#689 톡픽 상세 조회 API 응답에서 storedNames를 fileIds로 변경
  src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/dto/BaseTalkPickFields.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
Labels: ✨ feature, D-0

#692 TempTalkPickDto 공통 필드 분리
  src/main/java/balancetalk/talkpick/dto/BaseTalkPickFields.java
  src/main/java/balancetalk/talkpick/dto/SearchTalkPickResponse.java
  src/main/java/balancetalk/talkpick/dto/TempTalkPickDto.java
Labels: 🪄 refactor, D-0

#695 톡픽 임시 저장 시 모든 필드에 대한 공백 허용
  src/main/java/balancetalk/talkpick/domain/TempTalkPick.java
  src/main/java/balancetalk/talkpick/dto/BaseTalkPickFields.java
  src/main/java/balancetalk/talkpick/dto/BaseTempTalkPickFields.java
  src/main/java/balancetalk/talkpick/dto/TempTalkPickDto.java
Labels: ✨ feature, 🪄 refactor, D-0

#696 톡픽 생성 시 파일 ID 목록을 전달하지 않을 때 발생하는 오류 해결
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/application/TempTalkPickService.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/talkpick/dto/TempTalkPickDto.java
Labels: 🛠️ fix, D-0

#707 프론트 도메인 CORS 허용 완료
  src/main/java/balancetalk/global/config/SecurityConfig.java
Labels: ⚙️ chore, D-0

#708 톡픽 투표 비회원 접근 제한
  src/main/java/balancetalk/vote/application/VoteTalkPickService.java
  src/main/java/balancetalk/vote/presentation/VoteTalkPickController.java
  src/test/java/balancetalk/vote/application/VoteTalkPickServiceTest.java
Labels: ✨ feature, D-0

#709 톡픽 생성과 수정 요청 DTO 분리
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
Labels: 🪄 refactor, D-0

#711 리소스 삭제 시 관련 이미지 파일도 삭제되도록 구현
  src/main/java/balancetalk/file/domain/FileHandler.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
Labels: ✨ feature, D-0

#716 톡픽 수정, 임시 저장 시 이미지 파일 처리 전략 개선
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/application/TempTalkPickService.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/talkpick/dto/TempTalkPickDto.java
Labels: ✨ feature, D-0

#715 밸런스게임 URI 변경 (스웨거) 완료
  src/main/java/balancetalk/game/presentation/SearchGameController.java
  src/main/java/balancetalk/member/presentation/MyPageController.java
Labels: D-0

#729 선택지 B 반환 함수 구현 코드에서 오타 수정
  src/main/java/balancetalk/talkpick/dto/BaseTempTalkPickFields.java
Labels: 🛠️ fix, D-0

#713 밸런스 게임 임시 저장 기능 구현
  src/main/java/balancetalk/file/domain/FileType.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/application/TempGameService.java
  src/main/java/balancetalk/game/domain/TempGame.java
  src/main/java/balancetalk/game/domain/TempGameOption.java
  src/main/java/balancetalk/game/domain/TempGameSet.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/game/dto/TempGameDto.java
  src/main/java/balancetalk/game/dto/TempGameOptionDto.java
  src/main/java/balancetalk/game/dto/TempGameSetDto.java
  src/main/java/balancetalk/member/domain/Member.java
Labels: 🪄 refactor, D-0

#735 회원정보 수정 API 구현 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/file/domain/FileHandler.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/member/dto/MemberDto.java
  src/main/java/balancetalk/member/presentation/MemberController.java
  src/test/java/balancetalk/member/application/MemberServiceTest.java
Labels: ✨ feature, D-0

#745 imgUrl 생성 방식을 URI 대신 문자열 조합으로 변경
  src/main/java/balancetalk/file/domain/File.java
  src/main/java/balancetalk/file/domain/FileHandler.java
  src/main/java/balancetalk/file/domain/FileProcessor.java
Labels: 🛠️ fix, D-0

#741 회원 단일 조회 시 이메일 반환 (프론트 요청) 완료
  src/main/java/balancetalk/member/dto/MemberDto.java
Labels: ✨ feature

#748 밸런스 게임 생성시 gameSetId 리턴
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/presentation/GameController.java
  src/main/java/balancetalk/member/dto/MemberDto.java
Labels: D-0

#753 회원정보 수정 - 이미지 업로드 로직 수정 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/dto/MemberDto.java
Labels: 🛠️ fix, D-0

#758 회원 프로필 이미지 관련 로직 구현
  src/main/java/balancetalk/file/domain/FileHandler.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/member/dto/MemberDto.java
Labels: ✨ feature, D-0

#760 PICK-O 프렌즈 관련 API 개발
  config/checkstyle/checkstyle.xml
  src/main/java/balancetalk/file/domain/FileType.java
  src/main/java/balancetalk/friends/application/FriendsService.java
  src/main/java/balancetalk/friends/domain/Friends.java
  src/main/java/balancetalk/friends/domain/FriendsRepository.java
  src/main/java/balancetalk/friends/dto/FriendsDto.java
  src/main/java/balancetalk/friends/presentation/FriendsController.java
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/member/domain/Member.java
Labels: ✨ feature, D-0

#764 게임 수정 API 호출 시 이미지 중첩되는 문제 해결
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/GameOption.java
  src/main/java/balancetalk/game/dto/GameOptionDto.java
Labels: 🛠️ fix, D-0

#766 프로필 이미지를 프렌즈 이미지로 등록 시 해당 파일이 업데이트되지 않도록 수정
  src/main/java/balancetalk/file/domain/File.java
  src/main/java/balancetalk/member/application/MemberService.java
Labels: ✨ feature, D-0

#739 isNewRequest 메서드를 json 직렬화 대상에서 제외
  src/main/java/balancetalk/talkpick/dto/TempTalkPickDto.java
Labels: ⚙️ chore, D-0

#773 임시저장 업데이트 시 메인, 서브태그 값 업데이트
  src/main/java/balancetalk/game/application/TempGameService.java
  src/main/java/balancetalk/game/domain/TempGameSet.java
Labels: D-0

#762 인기순 게시글 조회 API 구현
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/repository/GameSetRepository.java
  src/main/java/balancetalk/game/presentation/GameController.java
Labels: D-0

#777 게임 수정 시 파일 처리 로직에서 발생하는 문제 해결
  src/main/java/balancetalk/game/application/GameService.java
Labels: 🛠️ fix, D-0
