Repository JECT-Study/PICK-O-Server, pull requests merged in 2024-09, with the labels that each got.

#563 톡픽 본문 요약 기능에 재요청 로직 추가
  build.gradle
  src/main/java/balancetalk/BalanceTalkApplication.java
  src/main/java/balancetalk/talkpick/application/SummaryContentService.java
Labels: ✨ feature, 👨🏻‍💻 backend

#565 알림 기능 추가 구현 완료
  src/main/java/balancetalk/bookmark/application/BookmarkGameService.java
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/global/notification/application/NotificationService.java
  src/main/java/balancetalk/global/notification/domain/NotificationMessage.java
  src/main/java/balancetalk/global/notification/domain/NotificationStandard.java
  src/main/java/balancetalk/global/notification/domain/NotificationTitleCategory.java
  src/main/java/balancetalk/global/notification/dto/NotificationDto.java
  src/main/java/balancetalk/vote/application/VoteGameService.java
  src/main/java/balancetalk/vote/application/VoteTalkPickService.java
Labels: ✨ feature, 👨🏻‍💻 backend

#568 알림 저장 기능 구현 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/notification/application/NotificationService.java
  src/main/java/balancetalk/global/notification/domain/Notification.java
  src/main/java/balancetalk/global/notification/domain/NotificationRepository.java
  src/main/java/balancetalk/global/notification/dto/NotificationDto.java
  src/main/java/balancetalk/global/notification/presentation/NotificationController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#569 마이페이지 날짜 데이터 형식 변경 완료
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/global/notification/application/NotificationService.java
  src/main/java/balancetalk/global/notification/dto/NotificationDto.java
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
Labels: ✨ feature, 👨🏻‍💻 backend

#573 URL에서 대문자 대신 하이픈으로 수정
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/repository/GameTagRepository.java
  src/main/java/balancetalk/game/presentation/GameTagController.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#576 알림 기능 응답 필드 수정 완료
  src/main/java/balancetalk/global/notification/dto/NotificationDto.java
  src/main/java/balancetalk/global/notification/presentation/NotificationController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#582 톡픽 상세 조회 응답에 이미지 storedName 추가
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
Labels: ✨ feature, 👨🏻‍💻 backend

#586 로그 시간을 한국 시간대로 표시되도록 수정
  src/main/resources/logs/log4j2-dev.yml
Labels: 🐛 bug, 🪄 refactor, 👨🏻‍💻 backend

#588 댓글 좋아요 취소 후 myLike 필드의 값이 변경되지 않는 에러 해결
  src/main/java/balancetalk/comment/application/CommentService.java
Labels: 👨🏻‍💻 backend, 🛠️ fix

#590 ERD구조 변경에 따라 밸런스 게임 구조 리팩토링
  src/main/java/balancetalk/bookmark/application/BookmarkGameService.java
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/game/domain/MainTag.java
  src/main/java/balancetalk/game/domain/repository/GameRepository.java
  src/main/java/balancetalk/game/domain/repository/GameSetRepository.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/presentation/GameController.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/vote/application/VoteGameService.java
Labels: ⚙️ chore, 🪄 refactor, 👨🏻‍💻 backend

#592 밸런스 세트 조회 로직 수정
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/game/presentation/GameController.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#596 refactor: 회원 조회 시 프로필 이미지 필드 추가
  src/main/java/balancetalk/member/dto/MemberDto.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#594 코드 품질 관리 자동화를 위한 Sonarqube 도입
  .github/workflows/ci.yml
  build.gradle
Labels: ⚙️ chore, 👨🏻‍💻 backend

#598 밸런스 게임 목록 최신순, 인기순 기능 리팩토링
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/repository/GameSetRepository.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/game/presentation/GameController.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#603 답글 기능 분리, 댓글 기능 수정 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/comment/domain/CommentRepository.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/comment/presentation/CommentController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#604 밸런스게임 검색 구현 완료
  src/main/java/balancetalk/game/application/SearchGameService.java
  src/main/java/balancetalk/game/domain/repository/GameRepository.java
  src/main/java/balancetalk/game/dto/SearchGameResponse.java
  src/main/java/balancetalk/game/presentation/SearchGameController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#607 톡픽 생성 API 응답을 톡픽 ID로 변경
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/application/TempTalkPickService.java
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#608 마이페이지 - 내가 저장한 밸런스게임 기능 수정 및 투표 중도 복귀 기능 구현
  src/main/java/balancetalk/bookmark/application/BookmarkGameService.java
  src/main/java/balancetalk/bookmark/domain/Bookmark.java
  src/main/java/balancetalk/bookmark/domain/BookmarkGenerator.java
  src/main/java/balancetalk/bookmark/domain/BookmarkRepository.java
  src/main/java/balancetalk/bookmark/domain/BookmarkType.java
  src/main/java/balancetalk/bookmark/presentation/BookmarkGameController.java
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameReader.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/vote/application/VoteGameService.java
Labels: ✨ feature, 👨🏻‍💻 backend
