Repository JECT-Study/PICK-O-Server, pull requests merged in 2024-10, with the labels that each got.

#611 밸런스게임 재투표 가능 구현 완료
  src/main/java/balancetalk/bookmark/application/BookmarkGameService.java
  src/main/java/balancetalk/bookmark/domain/Bookmark.java
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameOption.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/game/presentation/SearchGameController.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/vote/application/VoteGameService.java
  src/main/java/balancetalk/vote/domain/VoteRepository.java
Labels: ✨ feature, 👨🏻‍💻 backend

#615 밸런스 게임 수정, 삭제 구현
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameOption.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/dto/GameOptionDto.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/game/dto/TempGameOptionDto.java
  src/main/java/balancetalk/game/presentation/GameController.java
  src/main/java/balancetalk/member/domain/Member.java
Labels: ✨ feature, 👨🏻‍💻 backend

#619 SonarQube 서버를 분리함으로써, 관련 설정 추가 및 CI 워크 플로우 수정
  .github/workflows/ci.yml
  build.gradle
Labels: ⚙️ chore, 👨🏻‍💻 backend

#620 북마크 기능 분리 완료
  src/main/java/balancetalk/bookmark/application/BookmarkGameService.java
  src/main/java/balancetalk/bookmark/application/BookmarkTalkPickService.java
  src/main/java/balancetalk/bookmark/domain/BookmarkGenerator.java
  src/main/java/balancetalk/bookmark/domain/BookmarkRepository.java
  src/main/java/balancetalk/bookmark/domain/BookmarkType.java
  src/main/java/balancetalk/bookmark/domain/GameBookmark.java
  src/main/java/balancetalk/bookmark/domain/GameBookmarkRepository.java
  src/main/java/balancetalk/bookmark/domain/TalkPickBookmark.java
  src/main/java/balancetalk/bookmark/domain/TalkPickBookmarkRepository.java
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
  src/main/java/balancetalk/vote/application/VoteGameService.java
  src/test/java/balancetalk/bookmark/application/TalkPickBookmarkServiceTest.java
  src/test/java/balancetalk/bookmark/domain/BookmarkTalkPickGeneratorTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#629 이미지 업로드 예외 처리 범위를 전체 파일로 변경
  src/main/java/balancetalk/file/application/FileService.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#625 댓글 기능 수정 (프론트 요청 사항) 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/comment/domain/CommentRepository.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/comment/presentation/CommentController.java
  src/main/java/balancetalk/member/domain/Member.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend, 🛠️ fix

#627 댓글 투표 선택지 반환 방식 수정 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
Labels: ✨ feature, 👨🏻‍💻 backend

#632 redirect url 주소를 3000포트에서 public ip주소로 변경
  src/main/java/balancetalk/global/oauth2/CustomSuccessHandler.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#635 redirect url 주소를 3000포트에서 public ip주소로 변경
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#633 밸런스게임 세트 조회 시 북마크 관련 에러 발생 해결
  src/main/java/balancetalk/game/application/GameService.java
Labels: 👨🏻‍💻 backend, 🛠️ fix

#636 밸런스게임 세트 투표수 구현 완료
  src/main/java/balancetalk/game/domain/GameSet.java
Labels: ✨ feature, 👨🏻‍💻 backend

#638 밸런스게임 세트에 title 필드 추가 완료
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/game/domain/repository/GameRepository.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/game/dto/SearchGameResponse.java
  src/main/java/balancetalk/global/notification/dto/NotificationDto.java
Labels: ✔︎ pull requests, 🪄 refactor, 👨🏻‍💻 backend

#641 SonarCloud 적용
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  build.gradle
Labels: ⚙️ chore, 👨🏻‍💻 backend

#643 checkstyle 플러그인 적용
  build.gradle
  config/checkstyle/checkstyle.xml
Labels: ⚙️ chore, 👨🏻‍💻 backend

#645 JWT 관련 의존성 변경
  build.gradle
Labels: ⚙️ chore, 👨🏻‍💻 backend

#649 Nullable 값 추가
  src/main/java/balancetalk/global/oauth2/service/CustomOAuth2UserService.java
Labels: 👨🏻‍💻 backend, 🛠️ fix

#651 톡픽 투표 삭제 요청 시 delete 문이 생성되지 않는 오류 해결
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
Labels: 👨🏻‍💻 backend, 🛠️ fix

#639 밸런스게임 알림 기능 리팩토링 완료
  src/main/java/balancetalk/bookmark/application/BookmarkGameService.java
  src/main/java/balancetalk/bookmark/application/BookmarkTalkPickService.java
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/global/notification/application/NotificationService.java
  src/main/java/balancetalk/global/notification/domain/NotificationHistory.java
  src/main/java/balancetalk/global/notification/domain/NotificationTitleCategory.java
  src/main/java/balancetalk/global/notification/dto/NotificationDto.java
  src/main/java/balancetalk/like/application/CommentLikeService.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/vote/application/VoteGameService.java
  src/main/java/balancetalk/vote/application/VoteTalkPickService.java
  src/test/java/balancetalk/bookmark/application/TalkPickBookmarkServiceTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#653 답글 작성 시 해당 톡픽 작성자가 예외처리되는 버그 해결 완료
  src/main/java/balancetalk/comment/application/CommentService.java
Labels: 👨🏻‍💻 backend, 🛠️ fix

#659 톡픽 관련 유효성 검증 애노테이션 추가
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
  src/main/java/balancetalk/talkpick/presentation/TempTalkPickController.java
  src/main/java/balancetalk/vote/presentation/VoteTalkPickController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#660 밸런스게임 북마크 취소 후 카운트 수 적용하도록 수정, 밸런스게임 세트 조회 시 북마크 관련 로직 수정
  src/main/java/balancetalk/bookmark/application/BookmarkGameService.java
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/global/notification/domain/NotificationHistory.java
Labels: 🪄 refactor, 👨🏻‍💻 backend, 🛠️ fix

#662 밸런스게임 검색 예외처리 완료
  src/main/java/balancetalk/game/application/SearchGameService.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
Labels: ✨ feature, 👨🏻‍💻 backend

#666 마이페이지 밸런스게임 관련 미동작 버그 해결
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/game/domain/repository/GameRepository.java
  src/main/java/balancetalk/game/domain/repository/GameSetRepository.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/member/application/MyPageService.java
Labels: ✨ feature, 🛠️ fix

#672 불필요한 Enum 클래스 삭제.
  src/main/java/balancetalk/game/domain/Option.java
Labels: ⚙️ chore, D-1
