Repository JECT-Study/PICK-O-Server, pull requests merged in 2024-06, with the labels that each got.

#326 [Swagger] API 재설계에 따른 스웨거 업데이트 완료
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/dto/BestCommentResponse.java
  src/main/java/balancetalk/module/comment/dto/CommentRequest.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/comment/dto/ReplyResponse.java
  src/main/java/balancetalk/module/comment/presentation/CommentController.java
  src/main/java/balancetalk/module/post/dto/BalanceGameResponse.java
  src/main/java/balancetalk/module/post/dto/TodayBalanceTalkResponse.java
  src/main/java/balancetalk/module/post/presentation/TodayBalanceTalkController.java
  src/main/java/balancetalk/module/vote/application/VoteService.java
  src/main/java/balancetalk/module/vote/dto/Option.java
  src/main/java/balancetalk/module/vote/dto/VoteRequest.java
  src/main/java/balancetalk/module/vote/dto/VotingStatusResponse.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
  src/test/java/balancetalk/module/vote/application/VoteServiceTest.java
Labels: ✔︎ pull requests, 📃 docs, 👨🏻‍💻 backend

#335 공통 응답 포맷 클래스 작성
  src/main/java/balancetalk/global/common/ApiResponse.java
Labels: ✨ feature, 👨🏻‍💻 backend

#330 refactor: Report, Notice 관련 코드 제거
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/Comment.java
  src/main/java/balancetalk/module/comment/presentation/CommentController.java
  src/main/java/balancetalk/module/file/domain/File.java
  src/main/java/balancetalk/module/file/domain/FileRepository.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/notice/application/NoticeService.java
  src/main/java/balancetalk/module/notice/domain/Notice.java
  src/main/java/balancetalk/module/notice/domain/NoticeRepository.java
  src/main/java/balancetalk/module/notice/dto/NoticeRequest.java
  src/main/java/balancetalk/module/notice/dto/NoticeResponse.java
  src/main/java/balancetalk/module/notice/presentation/NoticeController.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
  src/main/java/balancetalk/module/report/domain/Report.java
  src/main/java/balancetalk/module/report/domain/ReportCategory.java
  src/main/java/balancetalk/module/report/domain/ReportRepository.java
  src/main/java/balancetalk/module/report/dto/ReportRequest.java
  src/main/java/balancetalk/module/report/presentation/ReportController.java
  src/test/java/balancetalk/module/notice/application/NoticeServiceTest.java
  src/test/java/balancetalk/module/notice/presentation/NoticeControllerTest.java
Labels: 🪄 refactor

#332 댓글, 댓글 좋아요 Entity 수정 완료
  src/main/java/balancetalk/module/comment/domain/Comment.java
  src/main/java/balancetalk/module/comment/domain/CommentLike.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
Labels: ✔︎ pull requests, 🪄 refactor, 👨🏻‍💻 backend

#338 ExceptionHandler 통합
  src/main/java/balancetalk/global/common/ApiResponse.java
  src/main/java/balancetalk/global/exception/ConstraintViolationHandler.java
  src/main/java/balancetalk/global/exception/ErrorResponse.java
  src/main/java/balancetalk/global/exception/FileExceptionHandler.java
  src/main/java/balancetalk/global/exception/GlobalExceptionHandler.java
  src/main/java/balancetalk/global/exception/MethodArgumentException.java
Labels: 🪄 refactor, 👨🏻‍💻 backend

#344 모든 URL에 대해서 시큐리티 접근 허용하도록 수정
  src/main/java/balancetalk/BalanceTalkApplication.java
  src/main/java/balancetalk/global/config/SecurityConfig.java
Labels: 👨🏻‍💻 backend, 🛠️ fix

#346 톡픽 관련 엔티티 클래스 작성
  src/main/java/balancetalk/like/domain/Like.java
  src/main/java/balancetalk/like/domain/LikeType.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/domain/TalkPickFile.java
  src/main/java/balancetalk/talkpick/domain/ViewStatus.java
  src/main/java/balancetalk/vote/domain/Vote.java
  src/main/java/balancetalk/vote/domain/VoteOption.java
Labels: ✨ feature, 👨🏻‍💻 backend

#349 투표 관련 엔티티 클래스 작성
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/vote/domain/Vote.java
  src/main/java/balancetalk/vote/domain/VoteType.java
Labels: ✨ feature, 👨🏻‍💻 backend

#351 API 명세서 업데이트 (톡픽, 투표)
  src/main/java/balancetalk/file/presentation/FileController.java
  src/main/java/balancetalk/global/common/ApiResponse.java
  src/main/java/balancetalk/like/presentation/LikeTalkPickController.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDetailResponse.java
  src/main/java/balancetalk/talkpick/dto/TalkPickRequest.java
  src/main/java/balancetalk/talkpick/dto/TalkPickResponse.java
  src/main/java/balancetalk/talkpick/dto/TodayTalkPickResponse.java
  src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
  src/main/java/balancetalk/talkpick/presentation/TodayTalkPickController.java
  src/main/java/balancetalk/vote/dto/VoteRequest.java
  src/main/java/balancetalk/vote/dto/VoteResponse.java
  src/main/java/balancetalk/vote/presentation/VoteTalkPickController.java
Labels: ⚙️ chore, 👨🏻‍💻 backend

#352 댓글, 답글 작성 / 수정 / 삭제 리팩토링 완료
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/comment/domain/CommentRepository.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/comment/presentation/CommentController.java
  src/main/java/balancetalk/global/common/ApiResponse.java
  src/main/java/balancetalk/like/domain/Like.java
  src/main/java/balancetalk/like/domain/LikeType.java
  src/main/java/balancetalk/member/domain/Member.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/domain/TalkPickRepository.java
  src/main/java/balancetalk/vote/domain/VoteRepository.java
Labels: ✔︎ pull requests, ✨ feature, 🪄 refactor, 👨🏻‍💻 backend

#356 API 명세 업데이트 (댓글, 댓글 좋아요) 완료
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/comment/presentation/CommentController.java
  src/main/java/balancetalk/like/dto/LikeDto.java
  src/main/java/balancetalk/like/presentation/LikeController.java
Labels: ⚙️ chore, ✔︎ pull requests, 👨🏻‍💻 backend
