Repository JECT-Study/PICK-O-Server, pull requests merged in 2024-04, with the labels that each got.

#290 태그 검색 시 401 에러가 뜨던 오류 해결
  src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
  src/main/java/balancetalk/module/post/domain/PostRepository.java
Labels: ✔︎ pull requests, 🐛 bug, 👨🏻‍💻 backend

#292 게시글 좋아요 해제 로직 수정
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/post/application/PostService.java
Labels: ✔︎ pull requests, 🐛 bug, 👨🏻‍💻 backend

#296 Redis에 저장되는 값을 직렬화 하는 빈 추가
  src/main/java/balancetalk/global/config/RedisConfig.java
Labels: ✔︎ pull requests, 👨🏻‍💻 backend

#289 게시글 조회 시 조회수가 증가하지 않던 문제 해결
  src/main/java/balancetalk/module/post/application/PostService.java
Labels: 👨🏻‍💻 backend, 🛠️ fix

#287 댓글 목록 조회 API에서 댓글마다 답글 개수 포함하도록 수정 완료
  src/main/java/balancetalk/module/comment/domain/Comment.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
Labels: ✨ feature, 👨🏻‍💻 backend

#301 토큰 재발급 시 memberId가 토큰에 포함되지 않던 오류 수정
  src/main/java/balancetalk/global/config/CustomUserDetails.java
  src/main/java/balancetalk/global/config/MyUserDetailService.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/dto/TokenDto.java
Labels: ✔︎ pull requests, 👨🏻‍💻 backend, 🛠️ fix

#299 게시글, 댓글 신고 예외 처리 추가
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/report/domain/ReportRepository.java
Labels: ✔︎ pull requests, 👨🏻‍💻 backend

#294 회원 프로필 조회 기능 구현
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/dto/ProfileResponse.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#307 비회원 상태에서 프로필 조회 시 401에러
  src/main/java/balancetalk/module/member/dto/ProfileResponse.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
Labels: ✔︎ pull requests, 👨🏻‍💻 backend, 🛠️ fix

#311 마감시간 지난 게시글 조회 시 에러 발생
  src/main/java/balancetalk/module/post/domain/Post.java
Labels: ✔︎ pull requests, 👨🏻‍💻 backend, 🛠️ fix

#308 본인 게시글, 댓글을 신고할 때 에러 메세지 수정 및 데드라인 지난 게시글 조회 시 에러
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/report/domain/ReportRepository.java
Labels: ✔︎ pull requests, 👨🏻‍💻 backend, 🛠️ fix

#312 답글 목록 조회 응답에 작성자 ID 추가
  src/main/java/balancetalk/module/comment/dto/ReplyResponse.java
Labels: 👨🏻‍💻 backend, 🛠️ fix

#315 게시글 응답 DTO에 마감 여부 필드 추가
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
Labels: ✨ feature, 👨🏻‍💻 backend

#320 게시글 조회 시 마감 여부 필터링 로직 추가
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/domain/PostRepository.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
  src/test/java/balancetalk/module/post/application/PostServiceTest.java
Labels: ✨ feature, 👨🏻‍💻 backend

#321 Dev to main
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/PostRepository.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
  src/test/java/balancetalk/module/post/application/PostServiceTest.java
Labels: 💻 deploy, 👨🏻‍💻 backend

#323 요청 파라미터에 대한 swaager 설정 추가
  src/main/java/balancetalk/module/member/presentation/MemberController.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
Labels: ⚙️ chore, 👨🏻‍💻 backend

#324 Dev to main
  src/main/java/balancetalk/module/member/presentation/MemberController.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
Labels: 💻 deploy, 👨🏻‍💻 backend
