Repository JECT-Study/PICK-O-Server, pull requests merged in 2024-03, with the labels that each got.

#144 로그아웃 기능 구현
  build.gradle
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
  src/main/java/balancetalk/module/post/application/PostService.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#145 답글 depth를 1로 제한하는 기능 구현 완료
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 🧪 test, 👨🏻‍💻 backend

#148 북마크 API URL 개선 완료
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/bookmark/application/BookmarkService.java
  src/main/java/balancetalk/module/bookmark/domain/BookmarkRepository.java
  src/main/java/balancetalk/module/bookmark/dto/BookmarkRequest.java
  src/main/java/balancetalk/module/bookmark/presentation/BookmarkController.java
  src/test/java/balancetalk/module/post/application/BookmarkServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 🧪 test, 👨🏻‍💻 backend

#150 댓글 기능 memberId 사용 -> JWT 사용으로 수정
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/dto/CommentRequest.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 🧪 test, 👨🏻‍💻 backend

#157 멤버 단위 테스트, 예외 처리 테스트 추가
  src/main/java/balancetalk/module/authmail/dto/EmailRequest.java
  src/main/java/balancetalk/module/authmail/dto/EmailRequestDto.java
  src/main/java/balancetalk/module/authmail/dto/EmailVerification.java
  src/main/java/balancetalk/module/authmail/dto/EmailVerificationDto.java
  src/main/java/balancetalk/module/bookmark/presentation/BookmarkController.java
  src/test/java/balancetalk/module/bookmark/BookmarkServiceTest.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: ✔︎ pull requests, 🧪 test, 👨🏻‍💻 backend

#159 투표 생성 기능 단위 테스트 작성
  src/main/java/balancetalk/module/bookmark/presentation/BookmarkController.java
  src/test/java/balancetalk/module/bookmark/application/BookmarkServiceTest.java
  src/test/java/balancetalk/module/vote/application/VoteServiceTest.java
Labels: ✔︎ pull requests, 🧪 test, 👨🏻‍💻 backend

#162 투표 현황 조회 및 투표 수정 기능에 대한 단위 테스트 작성
  src/test/java/balancetalk/module/vote/application/VoteServiceTest.java
Labels: ✔︎ pull requests, 🧪 test, 👨🏻‍💻 backend

#153 게시글 기능 memberId 대신에 jwt를 사용하도록 수정
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/utils/SecurityUtils.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/PostRepository.java
Labels: ✔︎ pull requests, ✨ feature, 🪄 refactor, 👨🏻‍💻 backend

#164 댓글 기능 사용 시 해당 댓글이 URL의 게시글 id와 매칭 여부 검증 로직 추가 완료
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/bookmark/application/BookmarkService.java
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/CommentLike.java
  src/main/java/balancetalk/module/comment/domain/CommentRepository.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/comment/presentation/CommentController.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Labels: ✨ feature, 🧪 test, 👨🏻‍💻 backend

#169 불필요한 파라미터 제거 및 에러코드 추가
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
Labels: ✔︎ pull requests, 🪄 refactor, 👨🏻‍💻 backend

#161 멤버 서비스 클래스 단위 테스트 추가 및 예외 테스트 추가
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: ✔︎ pull requests, 🧪 test, 👨🏻‍💻 backend

#176 회원가입, 로그인 시 RequestBody, Response 수정
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/member/dto/JoinRequest.java
  src/main/java/balancetalk/module/member/dto/LoginResponse.java
  src/main/java/balancetalk/module/member/dto/TokenDto.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: ✔︎ pull requests, 🪄 refactor, 👨🏻‍💻 backend

#172 공지사항 작성 기능 구현 완료
  src/main/java/balancetalk/global/exception/ConstraintExceptionHandler.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/file/domain/File.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/notice/application/NoticeService.java
  src/main/java/balancetalk/module/notice/domain/Notice.java
  src/main/java/balancetalk/module/notice/domain/NoticeRepository.java
  src/main/java/balancetalk/module/notice/dto/NoticeRequest.java
  src/main/java/balancetalk/module/notice/dto/NoticeResponse.java
  src/main/java/balancetalk/module/notice/presentation/NoticeController.java
  src/test/java/balancetalk/module/notice/application/NoticeServiceTest.java
  src/test/java/balancetalk/module/notice/presentation/NoticeControllerTest.java
Labels: ✔︎ pull requests, ✨ feature, 🧪 test, 👨🏻‍💻 backend

#181 게시글 조회 API에 조회수 증가 로직 추가
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#182 스웨거 헤더 값으로 토큰 추가
  build.gradle
  src/main/java/balancetalk/global/config/SwaggerConfig.java
  src/main/java/balancetalk/module/file/presentation/FileController.java
  src/main/java/balancetalk/module/post/dto/PostRequest.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
  src/test/java/balancetalk/global/jwt/JwtTokenProviderTest.java
  src/test/java/balancetalk/global/redis/application/RedisServiceTest.java
  src/test/java/balancetalk/module/bookmark/application/BookmarkServiceTest.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
  src/test/java/balancetalk/module/vote/application/VoteServiceTest.java
Labels: ✔︎ pull requests, 🪄 refactor, 👨🏻‍💻 backend

#178 회원 닉네임 중복 검증 API 추가 및 테스트 코드 작성
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/member/domain/MemberRepository.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
  src/test/java/balancetalk/module/post/application/PostServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 🧪 test, 👨🏻‍💻 backend

#185 배포를 위해 dev 브랜치의 작업 내용을 main 브랜치로 push
  build.gradle
  src/main/java/balancetalk/global/config/SwaggerConfig.java
  src/main/java/balancetalk/global/exception/ConstraintExceptionHandler.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/global/utils/SecurityUtils.java
  src/main/java/balancetalk/module/authmail/application/MailService.java
  src/main/java/balancetalk/module/authmail/dto/EmailRequest.java
  src/main/java/balancetalk/module/authmail/dto/EmailVerification.java
  src/main/java/balancetalk/module/bookmark/application/BookmarkService.java
  src/main/java/balancetalk/module/bookmark/domain/BookmarkRepository.java
  src/main/java/balancetalk/module/bookmark/dto/BookmarkRequest.java
  src/main/java/balancetalk/module/bookmark/dto/BookmarkResponse.java
  src/main/java/balancetalk/module/bookmark/presentation/BookmarkController.java
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/CommentLike.java
  src/main/java/balancetalk/module/comment/domain/CommentRepository.java
  src/main/java/balancetalk/module/comment/dto/CommentRequest.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/comment/presentation/CommentController.java
  src/main/java/balancetalk/module/file/domain/File.java
  src/main/java/balancetalk/module/file/presentation/FileController.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/member/domain/MemberRepository.java
  src/main/java/balancetalk/module/member/dto/JoinRequest.java
  src/main/java/balancetalk/module/member/dto/LoginResponse.java
  src/main/java/balancetalk/module/member/dto/TokenDto.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
  src/main/java/balancetalk/module/notice/application/NoticeService.java
  src/main/java/balancetalk/module/notice/domain/Notice.java
  src/main/java/balancetalk/module/notice/domain/NoticeRepository.java
  src/main/java/balancetalk/module/notice/dto/NoticeRequest.java
  src/main/java/balancetalk/module/notice/dto/NoticeResponse.java
  src/main/java/balancetalk/module/notice/presentation/NoticeController.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/domain/PostRepository.java
  src/main/java/balancetalk/module/post/dto/BalanceOptionDto.java
  src/main/java/balancetalk/module/post/dto/PostRequest.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
  src/main/java/balancetalk/module/vote/application/VoteService.java
  src/main/java/balancetalk/module/vote/dto/VoteRequest.java
  src/test/java/balancetalk/global/jwt/JwtTokenProviderTest.java
  src/test/java/balancetalk/global/redis/application/RedisServiceTest.java
  src/test/java/balancetalk/module/bookmark/application/BookmarkServiceTest.java
  src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
  src/test/java/balancetalk/module/notice/application/NoticeServiceTest.java
  src/test/java/balancetalk/module/notice/presentation/NoticeControllerTest.java
  src/test/java/balancetalk/module/post/application/PostServiceTest.java
  src/test/java/balancetalk/module/vote/application/VoteServiceTest.java
Labels: 👨🏻‍💻 backend

#199 시큐리티 인증 URL 추가 및 에러 처리 추가
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/global/jwt/JwtUtils.java
  src/main/java/balancetalk/module/authmail/application/MailService.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/domain/MemberRepository.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
  src/main/java/balancetalk/module/vote/application/VoteService.java
  src/test/java/balancetalk/module/authmail/application/MailServiceTest.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: ✔︎ pull requests, 🐛 bug, 🪄 refactor, 👨🏻‍💻 backend

#207 회원가입 시 프로필 사진 선택 기능 구현 완료
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/member/dto/JoinRequest.java
  src/main/java/balancetalk/module/member/dto/MemberResponse.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#198 게시글 응답 DTO에 투표 여부 추가
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#206 인기 댓글 조회 기능 구현
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/CommentLike.java
  src/main/java/balancetalk/module/comment/domain/CommentRepository.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/comment/presentation/CommentController.java
  src/main/java/balancetalk/module/member/domain/Member.java
  src/main/java/balancetalk/module/member/domain/MemberRepository.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#203 인기 게시글 조회 기능 구현
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/PostRepository.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#195 게시글 조회 시 balanceOptionId를 응답하도록 구현 완료
  src/main/java/balancetalk/module/post/dto/BalanceOptionDto.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#218 Embedded Redis 적용
  build.gradle
  src/main/java/balancetalk/global/config/EmbeddedRedisConfig.java
  src/main/java/balancetalk/global/config/RedisConfig.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: ⚙️ chore, 👨🏻‍💻 backend

#205 비밀번호 찾기 기능 구현
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/authmail/application/MailService.java
  src/main/java/balancetalk/module/authmail/presentation/MailController.java
  src/main/java/balancetalk/module/member/domain/MemberRepository.java
  src/test/java/balancetalk/module/authmail/application/MailServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#186 공지사항 수정, 삭제 기능, 파일 첨부 구현 완료
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/file/domain/File.java
  src/main/java/balancetalk/module/file/domain/FileRepository.java
  src/main/java/balancetalk/module/notice/application/NoticeService.java
  src/main/java/balancetalk/module/notice/domain/Notice.java
  src/main/java/balancetalk/module/notice/dto/NoticeRequest.java
  src/main/java/balancetalk/module/notice/dto/NoticeResponse.java
  src/main/java/balancetalk/module/notice/presentation/NoticeController.java
  src/test/java/balancetalk/module/notice/application/NoticeServiceTest.java
  src/test/java/balancetalk/module/notice/presentation/NoticeControllerTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#219 토큰 값에 memberId 추가 및 기타 예외 처리
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/domain/MemberRepository.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
  src/test/java/balancetalk/module/notice/presentation/NoticeControllerTest.java
Labels: ✔︎ pull requests, 👨🏻‍💻 backend, 🛠️ fix

#211 게시글 응답 필드(이미지 url) 변경
  src/main/java/balancetalk/module/file/application/FileService.java
  src/main/java/balancetalk/module/file/domain/File.java
  src/main/java/balancetalk/module/file/presentation/FileController.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/dto/BalanceOptionRequest.java
  src/main/java/balancetalk/module/post/dto/BalanceOptionResponse.java
  src/main/java/balancetalk/module/post/dto/PostRequest.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
  src/test/java/balancetalk/module/post/application/PostServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#233 게시글 검색, 태그 검색 기능 구현
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/PostRepository.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
  src/test/java/balancetalk/module/post/application/PostServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#209 마이페이지 본인이 작성한 게시글, 댓글 조회 기능 구현
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/CommentRepository.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/member/presentation/MyPageController.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/PostRepository.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#214 마이페이지 본인이 투표한 게시글, 즐겨찾기한 게시글 조회 기능 구현
  src/main/java/balancetalk/module/bookmark/domain/Bookmark.java
  src/main/java/balancetalk/module/bookmark/domain/BookmarkRepository.java
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/CommentRepository.java
  src/main/java/balancetalk/module/member/presentation/MyPageController.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/PostRepository.java
  src/main/java/balancetalk/module/post/dto/BookmarkedPostResponse.java
  src/main/java/balancetalk/module/post/dto/VotedPostResponse.java
  src/main/java/balancetalk/module/vote/domain/VoteRepository.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#224 게시글 응답에 선택지별 득표 수, 게시글 전체 투표 수 반환 구현
  src/main/java/balancetalk/module/post/dto/BalanceOptionRequest.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#228 게시글 응답 시 투표한 선택지인 selectedOptionId 반환 구현 완료
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
Labels: ✨ feature, 👨🏻‍💻 backend

#230 게시글 및 댓글 응답시 사용자 프로필 이미지 반환 구현 완료
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#232 댓글 응답시 부모 댓글(원 댓글) id 응답 추가 구현 완료
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#242 게시글 응답에 각 선택지 ID 추가
  src/main/java/balancetalk/module/post/dto/BalanceOptionResponse.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#243 투표 생성 시 회원/비회원 구분 로직 개선
  src/main/java/balancetalk/module/vote/application/VoteService.java
  src/main/java/balancetalk/module/vote/dto/VoteRequest.java
  src/main/java/balancetalk/module/vote/presentation/VoteController.java
  src/test/java/balancetalk/module/vote/application/VoteServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#236 리프레시 토큰을 쿠키에 담는 기능 구현
  src/main/java/balancetalk/global/config/CorsConfig.java
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/dto/MemberResponse.java
  src/main/java/balancetalk/module/member/dto/TokenDto.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
  src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#239 공지사항, 마이페이지 시작 페이지 번호 수정 완료
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/module/member/presentation/MyPageController.java
  src/main/java/balancetalk/module/notice/presentation/NoticeController.java
Labels: ✨ feature, 👨🏻‍💻 backend

#249 댓글 목록 조회 시 답글 제외
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/domain/CommentRepository.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#248 게시글 목록 조회 시 추천수를 기준으로 내림차순 정렬하는 기능 구현
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#263 로그인 후 게시글 조회 시 에러 발생 해결
  src/main/java/balancetalk/module/post/dto/PostResponse.java
Labels: ✔︎ pull requests, 👨🏻‍💻 backend, 🛠️ fix

#269 스웨거 문서 수정 및 시큐리티 URL 허용
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/module/authmail/presentation/MailController.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
Labels: ✔︎ pull requests, 🪄 refactor, 👨🏻‍💻 backend

#258 클라이언트에 올바르게 토큰 에러 정보를 보여주도록 수정
  src/main/java/balancetalk/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
Labels: ✔︎ pull requests, 🪄 refactor, 👨🏻‍💻 backend

#271 게시글 조회 응답에 댓글 개수 추가
  src/main/java/balancetalk/module/post/domain/Post.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
Labels: ✨ feature, 👨🏻‍💻 backend

#253 마이페이지 API 응답 수정 완료
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/member/dto/MyPageResponse.java
  src/main/java/balancetalk/module/member/presentation/MyPageController.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/dto/BookmarkedPostResponse.java
  src/main/java/balancetalk/module/post/dto/VotedPostResponse.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#264 쿠키를 이용하여 리프레시 토큰을 추출하고 액세스 토큰을 재발급 하는 방법으로 구현
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/presentation/MemberController.java
Labels: ✔︎ pull requests, 🪄 refactor, 👨🏻‍💻 backend

#255 게시글, 댓글 신고 기능 구현
  src/main/java/balancetalk/module/authmail/dto/EmailRequest.java
  src/main/java/balancetalk/module/authmail/dto/EmailVerification.java
  src/main/java/balancetalk/module/comment/application/CommentService.java
  src/main/java/balancetalk/module/comment/dto/CommentResponse.java
  src/main/java/balancetalk/module/comment/presentation/CommentController.java
  src/main/java/balancetalk/module/file/dto/FileResponse.java
  src/main/java/balancetalk/module/member/application/MemberService.java
  src/main/java/balancetalk/module/member/dto/JoinRequest.java
  src/main/java/balancetalk/module/member/dto/LoginRequest.java
  src/main/java/balancetalk/module/member/dto/MemberResponse.java
  src/main/java/balancetalk/module/post/application/PostService.java
  src/main/java/balancetalk/module/post/dto/BalanceOptionRequest.java
  src/main/java/balancetalk/module/post/dto/BalanceOptionResponse.java
  src/main/java/balancetalk/module/post/dto/PostRequest.java
  src/main/java/balancetalk/module/post/dto/PostResponse.java
  src/main/java/balancetalk/module/post/dto/PostTagDto.java
  src/main/java/balancetalk/module/post/presentation/PostController.java
  src/main/java/balancetalk/module/report/domain/Report.java
  src/main/java/balancetalk/module/report/domain/ReportRepository.java
  src/main/java/balancetalk/module/report/dto/ReportRequest.java
  src/main/java/balancetalk/module/report/presentation/ReportController.java
  src/main/java/balancetalk/module/vote/dto/VoteRequest.java
Labels: ✔︎ pull requests, ✨ feature, 👨🏻‍💻 backend

#282 게시글 작성 할때 데드라인에서 @JsonFormat 수정
  src/main/java/balancetalk/module/post/dto/PostRequest.java
Labels: 🐛 bug, 👨🏻‍💻 backend
