Repository JECT-Study/PICK-O-Server, pull requests merged in 2025-01, with the labels that each got.

#837 비동기 메서드에서 엔티티 객체를 직접 조회하도록 수정하여 트랜잭션 반영 문제 해결
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/domain/TalkPickSummarizer.java
Labels: 🛠️ fix, D-0

#841 actuator, 프로메테우스 설정 추가
  build.gradle
Labels: ⚙️ chore, D-0

#838 토큰 재발급 이슈 처리
  src/main/java/balancetalk/global/config/SecurityConfig.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
  src/main/java/balancetalk/global/jwt/CustomLogoutHandler.java
  src/main/java/balancetalk/global/jwt/CustomSuccessHandler.java
  src/main/java/balancetalk/global/jwt/JwtTokenProvider.java
  src/main/java/balancetalk/member/application/MemberService.java
  src/main/java/balancetalk/member/presentation/MemberController.java
Labels: 🛠️ fix, D-0

#851 스케줄링을 통해 요약에 실패한 톡픽들에 대한 요약 작업 재수행 기능 구현
  src/main/java/balancetalk/talkpick/application/TalkPickScheduleService.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/application/TodayTalkPickService.java
  src/main/java/balancetalk/talkpick/domain/TalkPickSummarizer.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryCustom.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
Labels: ✨ feature, 🪄 refactor, D-1

#861 소셜 로그인 리다이렉트 수정
  src/main/java/balancetalk/global/jwt/CustomSuccessHandler.java
  src/main/java/balancetalk/global/oauth2/service/CustomOAuth2UserService.java
Labels: 🐛 bug, D-0

#864 밸런스 게임 작성자 필드값 추가
  src/main/java/balancetalk/game/domain/Game.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/dto/GameSetDto.java
  src/main/java/balancetalk/game/dto/SearchGameResponse.java
Labels: ✨ feature, D-0

#863 밸런스 게임 조회수가 증가하지 않는 이슈
  src/main/java/balancetalk/game/application/GameService.java
Labels: 🛠️ fix, D-0

#867 톡픽 요약 실패 처리 스케줄링 작업 임시 off
  src/main/java/balancetalk/talkpick/application/TalkPickScheduleService.java
Labels: ⚙️ chore, D-0

#855 톡픽 댓글에서 톡픽 작성자의 댓글 이외 댓글이 회색 처리 되는 이슈 해결
  src/main/java/balancetalk/comment/application/CommentService.java
  src/main/java/balancetalk/comment/domain/Comment.java
  src/main/java/balancetalk/comment/dto/CommentDto.java
  src/main/java/balancetalk/vote/application/VoteTalkPickService.java
Labels: 🗂️ db, 🛠️ fix, D-0

#865 밸런스게임 검색 성능 향상 완료
  src/main/java/balancetalk/game/application/SearchGameService.java
  src/main/java/balancetalk/game/domain/repository/GameRepository.java
  src/main/java/balancetalk/global/exception/ErrorCode.java
Labels: ✨ feature, D-0

#871 비동기 처리 시 메서드를 직접 호출하는 코드를 이벤트 발행으로 변경
  src/main/java/balancetalk/talkpick/application/TalkPickFileService.java
  src/main/java/balancetalk/talkpick/application/TalkPickScheduleService.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/application/TalkPickSummaryService.java
  src/main/java/balancetalk/talkpick/domain/event/TalkPickCreatedEvent.java
  src/main/java/balancetalk/talkpick/domain/event/TalkPickDeletedEvent.java
  src/main/java/balancetalk/talkpick/domain/event/TalkPickEventHandler.java
  src/main/java/balancetalk/talkpick/domain/event/TalkPickUpdatedEvent.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryCustom.java
  src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
  src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
Labels: 🪄 refactor, 🛠️ fix, D-0

#877 내가 투표한 게임 조회 시 gameSetId가 모두 0으로 통일되는 버그 해결
  src/main/java/balancetalk/game/dto/GameDto.java
Labels: 🛠️ fix, D-0
