Repository JECT-Study/PICK-O-Server, pull requests merged in 2025-02, with the labels that each got.

#880 내가 투표한 밸런스게임 조회 시 이슈 발생 해결
  src/main/java/balancetalk/bookmark/application/BookmarkGameService.java
  src/main/java/balancetalk/game/domain/repository/GameRepository.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/member/application/MyPageService.java
  src/main/java/balancetalk/vote/application/VoteGameService.java
  src/main/java/balancetalk/vote/domain/GameVote.java
  src/main/java/balancetalk/vote/domain/VoteRepository.java
  src/main/java/balancetalk/vote/dto/VoteGameDto.java
Labels: 🛠️ fix, D-0

#886 랜덤 밸런스 게임 실행 API 생성
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/domain/GameSet.java
  src/main/java/balancetalk/game/domain/repository/GameSetRepository.java
  src/main/java/balancetalk/game/domain/repository/GameSetRepositoryCustom.java
  src/main/java/balancetalk/game/domain/repository/GameSetRepositoryCustomImpl.java
  src/main/java/balancetalk/game/presentation/GameController.java
Labels: ✨ feature, D-0

#889 톡픽 상세 조회 응답에 작성자 프로필 이미지 URL 추가
  src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java
  src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java
  src/main/java/balancetalk/talkpick/application/TalkPickService.java
  src/main/java/balancetalk/talkpick/domain/TalkPick.java
  src/main/java/balancetalk/talkpick/domain/TalkPickImage.java
  src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
Labels: ✨ feature, D-0

#891 밸런스 게임 조회 시 NPE 문제 해결
  src/main/java/balancetalk/game/application/GameService.java
  src/main/java/balancetalk/game/dto/GameDto.java
  src/main/java/balancetalk/game/presentation/GameController.java
Labels: 🐛 bug, D-0
